Create Overview.md
YoubetDao/Blockchain-Technology-and-Application-Notes-2018 pull request #41
Opened 2024-09-12 15:34 UTC by x-wqs

2024-09-22 03:34 UTC, wfnuser requested changes

2024-09-22 03:34 UTC, wfnuser commented on ETH/Overview.md
> +- After Bitcoin's success, people wonder what else can be decentralized.The emergence of Ethereum has added the characteristic of decentralized contracts.
The following two line seems to be "How decentralized contract is inspired"? Not "hat is decentralized contract".

I think note should be concise and structured.

2024-09-22 03:58 UTC, wfnuser requested changes

2024-09-22 03:58 UTC, wfnuser commented on ETH/Overview.md
> +- In contracts with signatories from all over and no unified jurisdiction, judicial means are difficult for contract enforcement. Online crowdfunding with participants worldwide is an example.Even un
Make it concise is better. Like just a few points, like immutable, "must execute according to the code rules". You should make it look better, in a structured way.

2024-09-22 15:13 UTC, x-wqs commented
Related to issue #18

2024-09-23 15:31 UTC, wfnuser approved these changes

2024-09-23 15:31 UTC, merged

2024-09-23 15:32 UTC, wfnuser commented
> Related to issue #18

Should comment like `close #18`